# -*- coding: utf-8 -*-
"""Lab4_MorenoJuarez_GiulioMaximiliano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18lYoFKedL75BjfZwoOwa_By3Tmqfl0KT
"""

# lab 4 INSTITUTIONAL EMAIL GENERATOR
# STUDENTS WILL CREATE A FUNCTION

stored_password = "password123"  # Saved Password
max_login_attempts = 3           # Attempt Limit
login_attempts_count = 0         # Counter starts from 0


# Generate the email
def generate_email(name, lastname):
    email = f"{name.lower()}.{lastname.lower()}@utd.edu.mx"
    return email

# Make the password valid
def check_login_attempts(password_input):
    global login_attempts_count  # Modifies counter

    if password_input == stored_password:
        print("Login successful!")
        login_attempts_count = 0  # If its correct it restarts all the attempts
        return True
    else:
        login_attempts_count += 1  # Adds 1 if incorrect password
        print(f"Incorrect password. You have {max_login_attempts - login_attempts_count} attempts remaining.")
        return False

# --- Main program

# We ask for personal data
print("--- Student Registration ---")
name = input("Enter your first name: ")
lastname = input("Enter your last name: ")

# Generated and printed email based on what user typed in
generated_email = generate_email(name, lastname)
print("\nInstitutional email is: ", generated_email)
print(f"Estudiante: {name} {lastname}")

print("\n--- Login Section ---")

# Loop asking for password
while login_attempts_count < max_login_attempts:
    user_password = input("Enter your password: ")

    if check_login_attempts(user_password):
        break  # Goes through if password is correct
else:
    print("Maximum login attempts reached. Account locked.")