# -*- coding: utf-8 -*-
"""lab5_morenojuarez_giuliomaximiliano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byAyGZcuDBjDCe7R7KS2hXnwFES4X6VK
"""

# Función 1: Muestra el menú de géneros en la pantalla
def show_menu():
    print("\n=== STREAMSAGE ===")
    print("Selecciona un género:")
    print("1. Tecnología")
    print("2. Acción")
    print("3. Ciencia Ficción")

# Función 2: Pide al usuario su opción y la regresa validada
def get_genre():
    opcion = input("Opción: ")
    return opcion

# Función 3: Recibe el género y muestra las películas recomendadas
def recommend_content(genre):
    print("\nRecomendaciones:")
    if genre == "1":
        print("- Deadly Code")
        print("- El Imperio de los Datos")
    elif genre == "2":
        print("- Operation Delta")
        print("- Alerta Máxima")
    elif genre == "3":
        print("- Interestelar")
        print("- Cyberpunk 2077: Edgerunners")
    else:
        print("Opción no válida. Intenta de nuevo.")

#Reto Adicional: Permite calificar la recomendación
def rate_content():
    nota = input("\n¿Cómo calificarías estas recomendaciones? (1 al 5): ")
    print(f"¡Gracias! Guardamos tu calificación de {nota} estrellas.")

#PROGRAMA PRINCIPAL
def main():
    continuar = "Y"

    # Mientras el usuario quiera continuar el ciclo se repite
    while continuar.upper() == "Y":
        show_menu()              # 1. Mostramos el menú
        seleccion = get_genre()   # 2. Guardamos lo que el usuario eligió

        recommend_content(seleccion) # 3. Le damos sus películas

        # Se ejecuta el reto adicional
        rate_content()

        # 4. Preguntamos si quiere buscar de nuevo o salir
        continuar = input("\n¿Te gustaría realizar otra búsqueda? (Y/N): ")

    print("\n¡Gracias por usar nuestro sistema de recomendación!")

# Inicia el programa
main()