# -*- coding: utf-8 -*-
"""lab7_morenojuarez_giuliomaximiliano

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FakmlRjqJlh2emXbEXnFhADM_MF8kCMb
"""

"""lab7_morenojuarez_giuliomaximiliano.ipynb"""

# Lab 7 - Which Programming Career Fits You?

# Función para pedir y validar la puntuación
def pedir_puntuacion(habilidad):
    while True:
        try:
            valor = int(input(f"Puntuación de {habilidad} (1-10): "))
            if 1 <= valor <= 10:
                return valor
            else:
                print("  ⚠ El valor debe estar entre 1 y 10. Intenta de nuevo.")
        except ValueError:
            print("  ⚠ Por favor ingresa un número entero.")

# Función para mostrar el reporte del estudiante
def mostrar_reporte(estudiante):
    print("\n========== Career Assessment Report ==========")
    print(f"Name:          {estudiante['name']}")
    print(f"Programming:   {estudiante['programming']}")
    print(f"Design:        {estudiante['design']}")
    print(f"Networking:    {estudiante['networking']}")
    print(f"Data Analysis: {estudiante['data_analysis']}")
    print("===============================================")

# Función para calcular y recomendar la carrera
def recomendar_carrera(estudiante):
    habilidades = {
        "programming":   estudiante["programming"],
        "design":        estudiante["design"],
        "networking":    estudiante["networking"],
        "data_analysis": estudiante["data_analysis"]
    }

    puntaje_maximo = max(habilidades.values())

    # Detectar empate
    mejores = [h for h, v in habilidades.items() if v == puntaje_maximo]

    # Condicionales para mostrar resultado
    if len(mejores) > 1:
        print("\n Recommended Career: Multiple Career Paths Identified")
    else:
        mejor = mejores[0]
        if mejor == "programming":
            carrera = "Software Developer"
        elif mejor == "design":
            carrera = "UI/UX Designer"
        elif mejor == "networking":
            carrera = "Network Administrator"
        elif mejor == "data_analysis":
            carrera = "Data Analyst"

        print(f"\n Recommended Career: {carrera}")
    print("===============================================\n")


# Pedir nombre al usuario
nombre = input("Ingresa tu nombre: ")

# Pedir las puntuaciones usando la función de validación
prog   = pedir_puntuacion("Programación")
diseno = pedir_puntuacion("Diseño")
redes  = pedir_puntuacion("Redes (Networking)")
datos  = pedir_puntuacion("Análisis de Datos")

# Guardar todo en el diccionario student
student = {
    "name":          nombre,
    "programming":   prog,
    "design":        diseno,
    "networking":    redes,
    "data_analysis": datos
}

# Mostrar información llamando a la función
mostrar_reporte(student)

# Encontrar y mostrar la mejor carrera llamando a la función
recomendar_carrera(student)