# -*- coding: utf-8 -*-
"""lab7_morenojuarez_giuliomaximiliano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKzyQX_0ASibmIWLx68sSaa1YmW6bVY2
"""

# Lab 7 - Which Programming Career Fits You?

# Sistema de recomendación de carreras usando diccionarios y condiciones

# Pedir nombre al usuario
nombre = input("Ingresa tu nombre: ")

# Pedir las puntuaciones de habilidades (validadas)
def pedir_puntuacion(habilidad):
    while True:
        try:
            valor = int(input(f"Puntuación de {habilidad} (1-10): "))
            if 1 <= valor <= 10:
                return valor
            else:
                print("  ⚠ El valor debe estar entre 1 y 10. Intenta de nuevo.")
        except ValueError:
            print("  ⚠ Por favor ingresa un número entero.")

prog       = pedir_puntuacion("Programación")
diseno     = pedir_puntuacion("Diseño")
redes      = pedir_puntuacion("Redes (Networking)")
datos      = pedir_puntuacion("Análisis de Datos")  #Extra credit

# Guardar todo en el diccionario
student = {
    "name":          nombre,
    "programming":   prog,
    "design":        diseno,
    "networking":    redes,
    "data_analysis": datos     # Extra credit
}

# Mostrar información del diccionario
print("\n========== Career Assessment Report ==========")
print(f"Name:          {student['name']}")
print(f"Programming:   {student['programming']}")
print(f"Design:        {student['design']}")
print(f"Networking:    {student['networking']}")
print(f"Data Analysis: {student['data_analysis']}")   # Extra credit
print("===============================================")

# Encontrar la mejor carrera
habilidades = {
    "programming":   student["programming"],
    "design":        student["design"],
    "networking":    student["networking"],
    "data_analysis": student["data_analysis"]   # Extra credit
}

puntaje_maximo = max(habilidades.values())

# Detectar empate
mejores = [h for h, v in habilidades.items() if v == puntaje_maximo]

# Mostrar resultado
if len(mejores) > 1:
    print("\n Recommended Career: Multiple Career Paths Identified")
else:
    mejor = mejores[0]
    if mejor == "programming":
        carrera = "Software Developer"
    elif mejor == "design":
        carrera = "UI/UX Designer"
    elif mejor == "networking":
        carrera = "Network Administrator"
    elif mejor == "data_analysis":
        carrera = "Data Analyst"         #Extra credit

    print(f"\n Recommended Career: {carrera}")

print("===============================================\n")