# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjBDNk-GKxVctzvCDMQT6Z4E24PpcoLT
"""

#Code A#
grades[80, 90, 70]
average= sum(grades) / len(grades)
print(average)

#Code B#
def_ calculate_avergae(data):
    return sum(data) / len(data)
grades = [80, 90, 70]
print(calculate_average(grades))

#Code C#
numbers= [1, 2, 3, 4, 5]
squares= list(map(lambda x: x**2, numbers))
print(squares)