# -*- coding: utf-8 -*-
"""LAB2_MorenoJuarez_GiulioMaximiliano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTb_dR91idjqeYFDRBP1u-w0m8PvmesE
"""

#CODE 1#
def multiply(a, b):
    return a*b
    print(multiply(3, 4))

#CODE 2#
counter = 0
for i in range (4):
    counter= counter + 1
    print(counter)

# CODE 3#
age = int(input("Enter your age: "))
if age >= 18:
    print("Adult")

#CODE 4#
a=3
b=4
temp=a
a=b
b=temp
print (a)
print (b)