# -*- coding: utf-8 -*-
"""Lab3_MorenoJuarez_GiulioMaximiliano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188pZXYYf77nNNAwa085WmseBEWDEmLu4

# Lab3. Programming Paradigms Comparison

**Student Name:** Giulio Maximiliano Moreno Juarez   
**Group:**  3A
**Date:** 21/5/26  

---

# Objective

You will solve the same problem using different programming paradigms.

The goal is to understand how the way you think and structure a solution changes depending on the paradigm.



# Required Paradigms

You must implement the solution using ALL of the following paradigms:

1. Imperative Programming  
2. Structured Programming (functions + control structures)  
3. Modular Programming  
4. Object-Oriented Programming (OOP)  
5. Functional Programming (basic level)


# Important Rules

- The SAME problem must be used in all paradigms.
- You must NOT copy-paste the same solution with small changes.
- Each paradigm must show a different way of structuring the solution.
- Each section must include:
  - explanation in your own words
  - working code
  - a personal modification
  - a short reflection


# Problem Description

Describe the problem you will solve:

```text
A system that calculates the average grade of students and determines if they pass or fail.

# 1. 1. Imperative Programming  

## Brief Explanation
It's a paradigm to work step by step instructions using variables and loops.


## Code Example
Complete the steps:
"""

# Given data
grades = [70, 80, 90]
total = 0
highest_grade = grades[0]  #  assumes the first grade is the highest

# 1. Calculates the sum and finds the highest grade using a loop
for grade in grades:
    total += grade

    # Imperative check to find the highest value
    if grade > highest_grade:
        highest_grade = grade

average = total / len(grades)

# 2. Determine pass or fail
if average >= 70:
    print("pass")
else:
    print("fail")

# 3. Print the results
print("Average: ", average)
print("Highest Grade: ", highest_grade)

"""## Your Modification
What did you change and why?

I modified the imperative loop to track the highest grade in the list simultaneously while accumulating the sum. I initialized a state variable highest_grade with the first element of the list, and inside the for loop, I added a conditional statement (if grade > highest_grade) to update it if a larger value is found. This was done to add more analytical depth to the student grade system while strictly remaining within the step-by-step state manipulation boundaries of the imperative paradigm.



## Reflection
What did you learn from this approach and how does it compare to others?

This approach highlights the nature of Imperative Programming, where the developer explicitly tells the machine how to do something cycle-by-cycle (e.g., manually checking and mutating state variables like total and highest_grade). Imperative programming means telling the computer exactly how to do something step-by-step using loops and variables. While it requires writing more code manually, it gives you complete control over how data is handled. In contrast, declarative or functional programming focuses on what you want to do by using built-in shortcuts like sum() or max(), hiding the underlying steps.

---
## 2. Structured Programming (functions + control structures)

## Brief Explanation
It uses functions to organize logic

## Code Example
Complete the steps:
"""

def calculate_mean(values):
    return sum(values) / len(values) if values else 0

def checking_status(avg):
    if avg >= 70:
        return "Pass"
    return "Fail"

# --- Modification: Dynamic input & Validation ---
grades = []
print("Enter grades (type '-1' to finish):")

while True:
    try:
        user_input = float(input("Enter grade: "))
        if user_input == -1:
            break
        if 0 <= user_input <= 100:
            grades.append(user_input)
        else:
            print("Please enter a valid grade between 0 and 100.")
    except ValueError:
        print("Invalid input. Please enter a number.")

# --- Execution ---
if grades:
    avg = calculate_mean(grades)
    status = checking_status(avg)
    # Formatted to 2 decimal places to fix trailing floats (e.g., 45.666666666666664)
    print(f"\nAverage: {avg:.2f}")
    print(f"Status: {status}")
else:
    print("No grades were entered.")

"""## Your Modification
What did you change and why?

To demonstrate a deeper application of structured programming, I modified the script to handle a dynamic list of grades input by the user, added input validation using a loop, and formatted the final average output to look cleaner.



## Reflection
What did you learn from this approach and how does it compare to others?

Through this approach, I learned that structured programming drastically improves code reusability and readability by isolating specific tasks—like calculations and condition checks—into dedicated, modular functions. By organizing logic this way, the code becomes much easier to debug and maintain compared to an unstructured, sequential script where logic is repeated and written in a single top-to-bottom block. When compared to Object-Oriented Programming (OOP), which bundles data and behaviors into complex object classes, this structured approach is far more straightforward and efficient for algorithmic or utility-based tasks. It strikes a perfect balance for this type of problem, utilizing clear control structures like loops and conditionals to manage data flow without the added overhead of managing object states.

---
## 3. Modular Programming

# Brief Explanation
It's a programming paradigm that focuses on breaking a large, complex program into smaller, independent, and reusable sub-programs or blocks of code called modules (or functions). Instead of writing one massive script, each module handles a specific, isolated task, making the code much easier to test, debug, and maintain.

# Code Example
Complete the steps:
"""

def calculate_average(grades):
    return sum(grades) / len(grades)

def determine_status(average):
    if average >= 6.0:
        return "Passed"
    return "Failed"

def process_student(name, grades):
    avg = calculate_average(grades)
    status = determine_status(avg)
    print(f"Name: {name} | Avg: {avg:.1f} | Status: {status}")

process_student("Sophia", [8.5, 7.0, 9.0])

"""# Modification

Added a defensive logic step to handle empty arrays, preventing a ZeroDivisionError, and implemented a critical grade threshold check where any single score below 4.0 triggers an automatic failure.

# Reflection
Highly readable and simple to debug. It maps directly to linear execution requirements, though managing data state across many modules can become difficult as complexity grows.


"""

def determine_strict_status(average, grades):
    if not grades:
        return "No Grades Provided"
    if any(grade < 4.0 for grade in grades):
        return "Failed (Critical Grade Drop)"
    return "Passed" if average >= 6.0 else "Failed"

grades = [10.0, 10.0, 3.5]
avg = calculate_average(grades) if grades else 0.0
print(f"Status: {determine_strict_status(avg, grades)}")

"""# Object-Oriented Programming (OOP)

# Explanation
OOP organizes code into blueprints called classes, which group specific data variables (attributes) with their related actions (methods). Instances of these classes, known as objects, manage their own data lifecycle. This structural paradigm relies on key mechanics like encapsulation (hiding internal data and restricting direct access), inheritance (reusing structure across related classes), and polymorphism (redefining actions across different objects).

# Code Example
"""

class Student:
    def __init__(self, name, grades):
        self.name = name
        self.grades = grades

    def get_average(self):
        return sum(self.grades) / len(self.grades)

    def get_status(self):
        return "Passed" if self.get_average() >= 6.0 else "Failed"

    def display(self):
        print(f"Name: {self.name} | Avg: {self.get_average():.1f} | Status: {self.get_status()}")

student = Student("Carlos", [5.0, 6.0, 5.5])
student.display()

"""# Modification

Implemented a specialized subclass via inheritance to handle attendance metrics, using encapsulated state logic to modify grading behavior based on engagement data.

# Reflection
Encapsulation ensures high code safety by preventing external parts of the application from directly modifying internal object states. Setting up classes requires more boilerplate, but it scales well for complex domain modeling.
"""

class StudentWithAttendance(Student):
    def __init__(self, name, grades, attendance):
        super().__init__(name, grades)
        self.attendance = attendance # Percentage out of 100

    def get_status(self):
        if self.attendance < 80:
            return "Failed (Attendance)"
        return super().get_status()

student2 = StudentWithAttendance("Lucia", [9.0, 9.5, 10.0], 75)
print(f"Name: {student2.name} | Status: {student2.get_status()}")

"""# Functional Programming

# Explanation
Functional programming treats computation as the evaluation of pure mathematical functions, avoiding side effects and state mutations. Data structures are treated as immutable; transforming data results in completely new structures rather than modifications to existing ones. Iteration is driven by higher-order functions—functions that accept or return other functions—such as map, filter, and reduce, discarding iterative tracking loops like for and while.
"""

# Initial product inventory data
inventory_data = [
    {"product": "Laptop", "price": 1200.0, "discount_pct": 10},
    {"product": "Mouse", "price": 25.0, "discount_pct": 0},
    {"product": "Monitor", "price": 300.0, "discount_pct": 15},
    {"product": "HDMI Cable", "price": 15.0, "discount_pct": 0}
]

# Basic calculation tools
calc_discount = lambda price, pct: price * (pct / 100)
calc_final_price = lambda price, pct: price - calc_discount(price, pct)

# Transforming each item into a pricing report
create_price_report = lambda item: {
    "product": item["product"],
    "original_price": item["price"],
    "final_price": calc_final_price(item["price"], item["discount_pct"]),
    "has_discount": "Yes" if item["discount_pct"] > 0 else "No"
}

# Generating the baseline list of reports using map
baseline_reports = list(map(create_price_report, inventory_data))
print(baseline_reports)

"""# Modification

Added a pure functional pipeline using data aggregation logic via reduce alongside a filter function to extract data sets matching complex selection metrics.

# Reflection

Completely declarative. Eliminating shared state changes and tracking variables removes common timing bugs and runtime concurrency issues, making it ideal for processing complex data transformations.
"""

from functools import reduce

inventory_data = [
    {"product": "Laptop", "price": 1200.0, "discount_pct": 10},
    {"product": "Mouse", "price": 25.0, "discount_pct": 0},
    {"product": "Monitor", "price": 300.0, "discount_pct": 15},
    {"product": "HDMI Cable", "price": 15.0, "discount_pct": 0}
]

calc_discount = lambda price, pct: price * (pct / 100)
calc_final_price = lambda price, pct: price - calc_discount(price, pct)

create_price_report = lambda item: {
    "product": item["product"],
    "original_price": item["price"],
    "final_price": calc_final_price(item["price"], item["discount_pct"]),
    "has_discount": "Yes" if item["discount_pct"] > 0 else "No"
}

all_reports = list(map(create_price_report, inventory_data))

# --- IDENTICAL MODIFICATION APPLIED HERE ---

# A) FILTERING: Extracting only items matching a metric (Items currently on sale)
# 'filter' acts as our sieve to capture only the products marked as "Yes" for discounts.
on_sale_items = list(filter(lambda item: item["has_discount"] == "Yes", all_reports))

# B) AGGREGATION WITH REDUCE: Gathering store-wide total financial metrics
# We initialize our blank scratchpad to keep track of the total retail value and item count.
financials_initial = {"total_store_value": 0.0, "total_items_counted": 0}

# This rule dictates how our scratchpad updates for every individual item processed
aggregation_logic = lambda accumulator, item: {
    "total_store_value": accumulator["total_store_value"] + item["final_price"],
    "total_items_counted": accumulator["total_items_counted"] + 1
}

# 'reduce' steps through the list, flattening the details into our single financial summary dict
aggregated_financials = reduce(aggregation_logic, all_reports, financials_initial)

# 4. Packaging the advanced pipeline output
final_pipeline_output = {
    "all_products": all_reports,
    "discounted_only": on_sale_items,
    "store_summary": aggregated_financials
}

print(final_pipeline_output)